### ISSUE TITLE
some functions can not be used when installed seurat v5

### ISSUE THREAD

**Issue by caodudu** [samuel-marsh/scCustomize#100]
because seurat v5 re-designed the structure of seurat object, many functions should be modified

**Comment by samuel-marsh** [comment]
Hi,

Yes, that is in the development plan.  I’m hoping to push one final pre-V5 version update later this week with bug fixes on dev branch.  I’m also currently waiting for a couple weeks of beta bug fixes on Seurat side before I dive into what is likely a large amount of time updating package.

once I start that process I will create a separate develop and developV5 branch to update as I go.

It would help though if you can let me know what functions are not working and what errors you are receiving so I can add them to to do list.

Thanks!
Sam

**Comment by samuel-marsh** [comment]
I have actually just opened new master issue to track and provide updates on V5 development.

if you could post info on functions and errors there that would be great!!

Thanks again!
Sam
