### ISSUE TITLE
Depicting the same number of cells per condition/orig.ident in DimPlot_scCustom

### ISSUE THREAD

**Issue by BaptLabRight** [samuel-marsh/scCustomize#105]
Dear Samuel,

Thank you so much for your amazing package.

I was wondering if it could be possible to add the possibility to depict the same number of cells (randomly) with the DimPlot_scCustom function in order to highlight differences of proportion of cells per condition or per orig.ident.

Thank you again.

**Comment by samuel-marsh** [comment]
Hi @BaptLabRight,

Sorry for the delay getting back to you!  In terms of this function and the goals of the package I think for now I'm inclined to leave out.  The reason being is that I think there are better ways to visually displayed differential abundance information than the dimensionality reduction plots (which can also be deceiving depending on density and settings for UMAP/tSNE).  If you want to do on your own it should be pretty straightforward to pull the reduction coordinates and metadata column and then randomly subsample and plot (or subsample the whole object).

Best,
Sam
