### ISSUE TITLE
Package is not available for R version 4.2.1

### ISSUE THREAD

**Issue by kboufea** [samuel-marsh/scCustomize#110]
Hi, I can successfully install `scCustomize` with R version 4.0.2 but not with version 4.2.1 where I get the following error message. Could you please let me know if you are planning to release a compatible version any time soon or if I need to downgrade my R version? Thank you.

```
Warning message:
package 'scCustomize' is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages 
```

**Comment by samuel-marsh** [comment]
Hi @kboufea 

It should be compatible with any R version >4.0.0.  Can you send me output of `sessionInfo()`

Thanks,
Sam

**Comment by kboufea** [comment]
Hi Sam, 

Thanks for looking into it. 

```
R version 4.2.1 (2022-06-23)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.5 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/openblas-pthread/libblas.so.3
LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/liblapack.so.3

locale:
 [1] LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_GB.UTF-8        LC_COLLATE=en_GB.UTF-8    
 [5] LC_MONETARY=en_GB.UTF-8    LC_MESSAGES=en_GB.UTF-8   
 [7] LC_PAPER=en_GB.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.2.1 tools_4.2.1   
```
Katerina

**Comment by samuel-marsh** [comment]
Hi Katerina,

Thanks very much!  Could you now also send full console output when you try running the install, including code run, all messages and errors?

Thanks!
Sam

**Comment by kboufea** [comment]
Hi Sam,

What I've posted above is the full error message but I repeat it below including the code run. 

```
install.packages("scCustomize", lib = "/home/kb2/R/x86_64-pc-linux-gnu-library/4.2")
Warning message:
package ‘scCustomize’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages 
```

Thanks, 
Katerina

**Comment by kboufea** [comment]
Hi Sam, 

Thanks for your suggestions. While installing from source the error message became more specific and it was actually due to Seurat's version and its dependencies that scCustomize was failing to install. All working now. 

Thanks for your help, 
Katerina

**Comment by samuel-marsh** [comment]
Hi Katerina,

Great!  Glad it worked!!

Best,
Sam
