### ISSUE TITLE
Question: what should I provide to add.cell.ids in Merge_Seurat_List()?

### ISSUE THREAD

**Issue by vertesy** [samuel-marsh/scCustomize#113]
Hey, 

thank you for sharing this great package! 
  
Question: what should I provide to add.cell.ids?

```r
> combined.obj <- scCustomize::Merge_Seurat_List(ls.Seurat, add.cell.ids = samples.short, merge.data = TRUE)
Error in merge.Seurat(x = x, y = y, add.cell.ids = add.cell.ids, merge.data = merge.data,  : 
  Please provide a cell identifier for each object provided to merge
> length(ls.Seurat)
[1] 9
> length(samples.short)
[1] 9
> is(samples.short)
 [1] "character"              
 [2] "vector"                 
...

```

in help
> 

add.cell.ids | A character vector of length(x = c(x, y)); appends the corresponding values to the start of each objects' cell names
-- | --

  
Thanks!
Abel

**Comment by vertesy** [comment]
Actually, does not need to be resolved, you can simply

```r
combined.obj <- merge(x = ls.Seurat[[1]], y = ls.Seurat[2:l(ls.Seurat)], add.cell.ids = samples.short)
```

**Comment by samuel-marsh** [comment]
Hey,

Thanks for kind words and thanks for pointing out bug.  I think that may have evolved with small changes made to `merge`.

I’ve always known about that alternate solution but goal of this function was to reduce code required and make easier for those less familiar with using [].

To that end I have pushed bug fix onto the release branch (sending to CRAN later today).  It adds both proper renaming as well as a check for overlapping cell names (as `add.cell.ids`) isn’t needed if all barcodes are already unique.

Best,
Sam
