### ISSUE TITLE
"Error in x$exists(name) : HDF5-API Errors" running "Read_CellBender_h5_Mat"

### ISSUE THREAD

**Issue by sahanda66** [samuel-marsh/scCustomize#114]
Hello Samuel,

In my attempt to use CellBender output for Seurat, I found that a scCustomize function can be useful.
So, I use:

`cellbender_mat <- Read_CellBender_h5_Mat(file_name = "E:/cellbender_output/W8409/W8409_out_filtered.h5")`

to convert my CellBender h5 to a readable file for Seurat.

However, I faced the following error, and I couldn't find the solution for it on the web.

```
Error in x$exists(name) : HDF5-API Errors:
    error #000: D:/a/rtools-packages/rtools-packages/mingw-w64-hdf5/src/hdf5-1.8.16/src/H5L.c in H5Lexists(): line 824: unable to get link info
        class: HDF5
        major: Symbol table
        minor: Object not found

    error #001: D:/a/rtools-packages/rtools-packages/mingw-w64-hdf5/src/hdf5-1.8.16/src/H5L.c in H5L_exists(): line 2765: path doesn't exist
        class: HDF5
        major: Symbol table
        minor: Object already exists

    error #002: D:/a/rtools-packages/rtools-packages/mingw-w64-hdf5/src/hdf5-1.8.16/src/H5Gtraverse.c in H5G_traverse(): line 861: internal path traversal failed
        class: HDF5
        major: Symbol table
        minor: Object not found

    error #003: D:/a/rtools-packages/rtools-packages/mingw-w64-hdf5/src/hdf5-1.8.16/src/H5Gtraverse.c in H5G_traverse_real(): line 755: component not found
        class: HDF5
        major: Symbol table
        minor: Object not found
```

I am using version 1.1.2 of scCustomize.
Are you familiar with this error? Do you have any solution to fix it?

Thanks,
Sahand

**Comment by samuel-marsh** [comment]
Hi Sahand,

Thanks for opening issue.  Can you let me know a couple of things:
- What version of CellBender you are using?
- The output of `sessionInfo()` after you receive the error.
- How was file pre-processed before CellBender (cellranger, starsolo, etc)
- Are you able to send me copy of the h5 file?  If so could you please share via googledrive to sccustomize@gmail.com?

Thanks!
Sam

**Comment by samuel-marsh** [comment]
Hi Sahand,

Try re-running things but with `feature_slot_name = "genes"`.  Looking at item 7 in your list output it appears your file is labeled “genes” instead of “features” which is the default.

Best,
Sam

**Comment by sahanda66** [comment]
It worked.

Thanks a lot,
Sahand

**Comment by samuel-marsh** [comment]
No problem, glad to help!
