### ISSUE TITLE
Cluster_Stats_All_Samples no longer working

### ISSUE THREAD

**Issue by emily-003** [samuel-marsh/scCustomize#117]
Hi there,

A few days ago, I was using the Cluster_Stats_All_Samples function. I have since updated R, and when I now try to use this function, I get the error message:
Error in Cluster_Stats_All_Samples(reclustered, group_by_var = "my_var") : 
  could not find function "Cluster_Stats_All_Samples"

This arises even though I have loaded the package. Help would be much appreciated.

Thank you in advance

**Comment by samuel-marsh** [comment]
Hi,

Can you please send me the output of `sessionInfo()` after you get the error?

Best,
Sam

**Comment by emily-003** [comment]
Don't worry - it was an issue with Seurat not opening! Thank you

**Comment by samuel-marsh** [comment]
Great, glad it’s working!
