### ISSUE TITLE
Request dot scale parameter for Clustered_DotPlot

### ISSUE THREAD

**Issue by Evenlyeven** [samuel-marsh/scCustomize#129]
Thank you for developing this package to make my life easier!

I was wondering if a dot scale parameter can be added to Clustered_DotPlot function. In DotPlot_scCustom function, which is ggplot2 based, the dot scale can be changed by using dot.scale from Seurat. But in Clustered_DotPlot, which is Complexheatmap based, I was not be able to change the dot scale. It would be great if you could add a dot scale feature to it. I would appreciate it if you could let me know how to change the dot scale too.

Thank you in advance!

**Comment by samuel-marsh** [comment]
Hi @Evenlyeven,

Thanks for kind words!  Let me take look at code and get back to you.  I agree that is potentially useful parameter to add.

Best,
Sam

**Comment by samuel-marsh** [comment]
Hi @Evenlyeven 

Just wanted to give you an update.  I have figured out how we can set new sizes for the points however, no trying to solve how to automate spacing the legend so that legend dots don't overlap each other and so that legend text is still aligned correctly.  Hopefully can get fix pushed sometime next week.

Best,
Sam

**Comment by samuel-marsh** [comment]
Hi @Evenlyeven,

Unfortunately, making this work is taking more bandwidth than I currently have.  If you are able to figure things out with complexHeatmap code I'm more than happy to entertain PR or if you post code I can implement that works too.

Sorry I don't have more time to implement currently!
Best,
Sam

**Comment by Evenlyeven** [comment]
> Hi @Evenlyeven,
> 
> Unfortunately, making this work is taking more bandwidth than I currently have. If you are able to figure things out with complexHeatmap code I'm more than happy to entertain PR or if you post code I can implement that works too.
> 
> Sorry I don't have more time to implement currently! Best, Sam

Thank you for letting me know! I will look into complexHeatmap code.
