### ISSUE TITLE
Calculate_joint_density

### ISSUE THREAD

**Issue by PrashINRA** [samuel-marsh/scCustomize#130]
Thanks for the scCustomize. It's wonderful for plotting.
However, I wanted to separate cells based on the joint density of a group of genes.
But with the function Plot_Density_Joint_Only, we can only plot, not separate cells based on a certain threshold of the joint density.

Thanks
Prashant

**Comment by samuel-marsh** [comment]
Hi Prashant,

Thanks for kind words!  So if I’m understanding correctly you want to get the joint density values from the plot so that you can filter cells based on those values?

Best,
Sam

**Comment by PrashINRA** [comment]
Thanks for the quick response.
yes, I would like to have joint_density values for all the cells in my Seurat object, so that I can separate a few cells based on certain threshold

**Comment by samuel-marsh** [comment]
Hi Prashant,

So the easiest way to do this is to extract data as you can from any ggplot2 object.
If you run:
```
plot <- Plot_Density_Joint_Only(seurat_object = pbmc, c("ACTB", "CD14"))
plot_data <- plot$data
```

Then you will get data.frame that contains the cell barcodes as rownames, UMAP coordinates, and the joint density values.
You can then filter the data.frame by threshold and pull the remaining rownames which can be used to filter Seurat object.

Best,
Sam
