### ISSUE TITLE
Prepare for upcoming Seurat v5 Release

### ISSUE THREAD

**Issue by Gesmira** [samuel-marsh/scCustomize#131]
Hi Sam, 
Hope you're well! I am opening this issue as a notification because `scCustomize` is [listed](https://cran.r-project.org/web/packages/Seurat/index.html) as a package that relies (depends/imports/suggests) on Seurat. 

I know you are already aware we recently released Seurat v5 as a beta in March of this year. We are now preparing to release Seurat v5 to CRAN, and plan to submit it on October 23rd. While we have tried our best to keep things backward-compatible, it is possible that updates to Seurat and SeuratObject might break your existing functionality or tests. We wanted to reach out before the new version is on CRAN, so that there's time to report issues/incompatibilities and prepare you for any changes in your code base that might be necessary.

As a reminder, to test the upcoming release, you can install Seurat from the `seurat5` branch using the instructions available on this page: https://satijalab.org/seurat/articles/install.

Thank you!
Seurat v5 team

**Comment by samuel-marsh** [comment]
Hi Seurat Team!

Thanks so much for the message.  I've begun preparing for V5 release and have switched the active dev branch of scCustomize to "develop_V5" and have my worklist of items to check in this issue (#101).  My plan for package to is to coordinate and also push v2.0.0 to CRAN on October 23rd (package will only depend on 4.3.0.1 so no issues in case Seurat's CRAN approval/check is slow).

Thus far in my use with my own analysis after updates in dev branch everything seems to be functioning correctly right now. The one major kick the tires tests I have to run (probably post SCG2023 next week) are running all the functionality through BPCells stored data as all my testing thus far is just with in memory objects as my current analysis is small enough to easy handle in memory.

I'll update in Seurat repo if I notice any further bugs during my testing.  I'll leave this issue open and post here in case I have question related to bug in scCustomize and have question about properly interfacing with Seurat.

Thanks!!
Sam

**Comment by Gesmira** [comment]
Hi Sam, 
Thanks, that's awesome to hear :) 
We'd be very interested to know how the BPCells testing goes for you and, of course, let us know if you run into any other problems. 
Best, 
Gesi
