### ISSUE TITLE
Split.plot feature for stacked violin plots.

### ISSUE THREAD

**Issue by Chanukya-Pavan** [samuel-marsh/scCustomize#134]
Hi, 

I started using the tools provided by your group and its great to see advancements. Anyway I'd like to see if split.plot feature can be added to the function stacked_violin_plot, as it would reduce the size of the image and would be a great feature to already existing one.
In case it's already there please let me know how can i get it done.

As an aesthetic feature how can I change the position of the feature name to center from top left of the image, which I feel would be a better look.

Thanks,
Chanukya

**Comment by samuel-marsh** [comment]
Hi Chanukya,

Thanks for kind words.  In terms of split.plot there are not currently plans to implement in stacked violin plot.  Its support is not under current dev from Seurat devs and there are problems with sometimes the violins switching and it lacks support for more than two groups.  So having individual violins for splits provides better visualization.

In terms of changing the feature name location I'm not sure right now how to go about that.  The feature names are part of y axis label on the plots and so not easily centered on x-axis above the plot.  There may be way to hack it into ggplot/patchwork to make it work but unsure.  To be honest given I'm one person operation maintaining and updating this package I don't think I have time to commit to this right now.  However, I'd be more than happy to welcome PR if you figure out mechanism to make it work.

Thanks!
Best,
Sam
