### ISSUE TITLE
Do sccustomize has an RRID entry?

### ISSUE THREAD

**Issue by wwzhang** [samuel-marsh/scCustomize#136]
Hi,

Do sccustomize has an RRID entry (https://scicrunch.org/resources/rin/rrids), if not could you submit one for us to cite in paper?

**Comment by samuel-marsh** [comment]
Hi,

I do not have an RRID entry currently but I can submit for one today.

In meantime and even once that is processed please also cite scCustomize in reference section as below:
Marsh SE (2021). scCustomize: Custom Visualizations & Functions for Streamlined Analyses of Single Cell Sequencing. https://doi.org/10.5281/zenodo.5706430.

See here as well:
https://samuel-marsh.github.io/scCustomize/articles/FAQ.html

Best,
Sam

**Comment by wwzhang** [comment]
that will help

Yeah, I cited the paper. but journals of cell press require the table of the things in method with identifiers, and right now most software and packages have RRIDs

**Comment by samuel-marsh** [comment]
Hi @wwzhang,

scCustomize has been accepted and now has RRID that should be searchable within a few days.  The ID is: scCustomize, RRID:SCR_024675.

I will update website with the additional citation info with release of v2.0.0 (submitting to CRAN tomorrow).

Thanks so much for using (and citing!) scCustomize!!

Best,
Sam
