### ISSUE TITLE
CellBender_Feature_Diff BUG: 'x' must be an array of at least two dimensions

### ISSUE THREAD

**Issue by JordanCTLin** [samuel-marsh/scCustomize#140]
The `CellBender_Feature_Diff` function would output error due to the update of seurat v5.
I guess the problem came from the `pluck` function

I have changed the code in `CellBender_Feature_Diff` from
```
  # Pull Cell Bender Counts
  cb_counts <- pluck(seurat_object, "assays", cell_bender_assay, "counts") %>%
```
to

```
# Pull Cell Bender Counts
  cb_counts <- seurat_object@assays$RNA$counts %>%
```

**Comment by samuel-marsh** [comment]
Hi @JordanCTLin,

This should already be resolved in the “release/2.0.0” branch (hope to get it CRAN early next week) but in meantime can install from GitHub.  If the issue persists after updating to that branch please let me know and I’ll reopen the issue.

Thanks,
Sam
