### ISSUE TITLE
Split_FeatureScatter

### ISSUE THREAD

**Issue by dgrutherford** [samuel-marsh/scCustomize#143]
Hi Sam, 

Thanks again for the split_featurescatter feature. I wonder if you can suggest a way to plot or even get as output Pearson coefficient each graph if using split.by= "disease" for instance?

Currently using: stat_cor(method= 'pearson')

This unfortunately only plots pearson on the right hand graph. 

Thanks again, 

Duncan

**Comment by samuel-marsh** [comment]
Hi Duncan,

Thanks for kind words.  Which version of scCustomize are you using?  In newest releases (v2.0.0+) I have merged that old function into `FeatureScater_scCustom`.  The plots should return correlations for each split as part of the plot by default.

Here is example:
```

pbmc <- pbmc3k.SeuratData::pbmc3k.final
pbmc <- UpdateSeuratObject(pbmc)

pbmc$sample_id <- sample(c("sample1", "sample2", "sample3"), size = ncol(pbmc),
                         replace = TRUE)


FeatureScatter_scCustom(seurat_object = pbmc, feature1 = "nFeature_RNA", feature2 = "nCount_RNA", split.by = "sample_id")
```

![image](https://github.com/samuel-marsh/scCustomize/assets/38284410/c2dae263-03f1-46cd-8af2-169e684eefc1)


Best,
Sam

**Comment by dgrutherford** [comment]
Hi Sam, 

Sorry for delay. Yes you are quite right I was using a older version <2. Now working with the update! Thanks so much again. 
Kind Regards
Duncan
