### ISSUE TITLE
Clustered_DotPlot using active.ident for 3 groups

### ISSUE THREAD

**Issue by EzequielD-86** [samuel-marsh/scCustomize#152]
I love this package, it has made my life easier and really helps drive the message of my data. 

I have one question/petition. It would be very useful to be able to do Clustered_DotPlot for 2 or more treatment groups on the same graph. For example, I have 3 treatment groups, and It would be perfect to show on the same plot, for each cell type,  gene expression side by side. For example "Basophils", Neutrophils and any other cell, would have 3 dots (one per treatment group) for each gene. That would be awesome. Thanks a lot!

P.s: found an old thread describing the issue https://github.com/satijalab/seurat/issues/5117

**Comment by samuel-marsh** [comment]
Hi @EzequielD-86,

Very sorry to the delay getting to this issue!
This feature will arrive with update to version 2.1 inside of current `Clustered_DotPlot` framework.  I hope to push the update to CRAN at end of the week.  I will update here when the feature is live.

Thanks!
Sam

**Comment by samuel-marsh** [comment]
Hi @EzequielD-86,

This function is now live in the dev branch.  Use 
```
devtools::install_github("samuel-marsh/scCustomize", ref = "file_cache_dev")
```

It is now part of the `Clustered_DotPlot` function.  Just use `split.by` parameter.  

I aim to push full release to CRAN next week but in meantime if you have any issues with function let me know and I will work on fixes asap.

Thanks,
Sam

**Comment by EzequielD-86** [comment]
Love it! Thank you!
