### ISSUE TITLE
Adding SpatialPlots

### ISSUE THREAD

**Issue by nina-hahn** [samuel-marsh/scCustomize#160]
Dear Samuel, 

I really like to use your package. It would be great to use it for spatial data (10x genomics) as well (e.g. SpatialPlot). 

Best, 
Nina

**Comment by samuel-marsh** [comment]
Hi Nina,

Thanks very much for the kind words.  I can look into adding some spatial plots (mostly just haven't had need or request for it yet).  What types of optimization would you be looking for in scCustomize versions of Seurat's spatial plots?

Best,
Sam

**Comment by nina-hahn** [comment]
Hi Sam, 

mainly an optimization of the coloring would help. In the DimPlot and Barplot I use the colorblind friendly ditto seq palette, but my spatial plots still have ggplot default colors that are difficult to distinguish. 

Best ,
Nina

**Comment by puapinyoying** [comment]
I also enjoy using scCustomize for the color optimization and more intuitive formatting of plots. Been waiting a year for an SpatialDimPlot_scCustom()!

**Comment by samuel-marsh** [comment]
@puapinyoying Thanks for additional vote!

@nina-hahn @puapinyoying I will try and get basic version into the next scCustomize release.  I'll update here when live in the develop branch.

Best,
Sam

**Comment by samuel-marsh** [comment]
@puapinyoying @nina-hahn 
Ok we are live in develop branch with `SpatialDimPlot_scCustom` v2.1.2.9040 or greater.

I'm going to close this issue as I test and move on to other things but if you run into any issues with new function or have suggestions please don't hesitate to open new issue!

Best,
Sam
