### ISSUE TITLE
Wrong R script "{overwrite = TRUE.} in Add_Cell_QC_Metrics 

### ISSUE THREAD

**Issue by chaesee1** [samuel-marsh/scCustomize#165]
```r
qc_orig <- Add_Cell_QC_Metrics(seurat_object = qc_orig, species = "human", overwrite = T)
```
#Adding Mito/Ribo Percentages to meta.data.
#Columns with "percent_mito" and/or "percent_ribo" already present in meta.data slot.
#! Overwriting those columns as `overwrite = TRUE.`
#Adding Cell Complexity #1 (log10GenesPerUMI) to meta.data.
#Adding Cell Complexity #2 (Top 50 Percentages) to meta.data.
#Calculating percent expressing top 50 for layer: counts
#Adding MSigDB Oxidative Phosphorylation, Apoptosis, and DNA Repair Percentages to meta.data.
#Adding IEG Percentages to meta.data.
#Layer with normalized data not present.
#ℹ Normalizing Data.
#Normalizing layer: counts
#Performing log-normalization
#0%   10   20   30   40   50   60   70   80   90   100%
#[----|----|----|----|----|----|----|----|----|----|
#**************************************************|
#Error in `lapply(text, glue_cmd, .envir = .envir)`:
#! Could not evaluate cli `{}` expression: `overwrite = TRUE.`.
#Caused by error in `eval(expr, envir = envir)`:
#! object 'TRUE.' not found
#Type .Last.error to see the more details.

<details>
  <summary> sessionInfo() output</summary>
  
```r
PASTE HERE sessionInfo() output
```
  
</details>

**Comment by samuel-marsh** [comment]
Hi @chaesee1,

Apologies for the bug!  This is now fixed in the develop branch (v2.1.2.9002).  If you have any issues running the function aftering updating to the dev branch please let me know and I'll reopen the issue.

Thanks!
Sam
