### ISSUE TITLE
Merge_Seurat_List() add.cell.ids for long Seurat object list

### ISSUE THREAD

**Issue by levinhein** [samuel-marsh/scCustomize#175]
Hi Marsh!

May I ask how would you add unique cell ids for a Seurat object list with a lot of Seurat objects inside (n=100)?

Manually writing `add.cell.ids = c("A", "B", "C) `as a parameter inside `Merge_Seurat_List()` is easy for small lists, but for large ones, it's troublesome.

I tried a for loop first, but it doesn't seem to work:

```
library(scCustomize)

### Add unique cell ids - dup;icate cell barcodes
for (i in names(ALL.list)) {
  ALL.list[[i]] <- RenameCells(ALL.list[[i]], 
                               add.cell.id = i) 
}

### Merge u
ALL <- Merge_Seurat_List(ALL.list)
```

```
Error in `Merge_Seurat_List()`:
! There are overlapping cell barcodes present in the input objects
ℹ Please rename cells or provide prefixes to `add.cell.ids` parameter to make unique.
```
Any recommendations are highly appreciated. Thank you!

**Comment by levinhein** [comment]
Hi Sam,

Thank you for this. It works to add unique cell barcodes on each dataset in the Seurat object list!

The only problem is that when doing `Merge_Seurat_List()`, my RStudio server keeps crashing. I've repeated it 6 times for the past 3 days and everything is unsuccessful. I also tried using the regular Serurat `merge() `function and still the same outcome. 

Do you have any solution for merging huge data? MY RStduio memory usage indicator is red (110 GiB) while the Seurat object list in the environment is 150 GB when I do the merging procedure. 


### Merge ALL DATA either by: 
A) `ALL.merged  <- Merge_Seurat_List(ALL.list)`
B) `ALL.merged <- merge(ALL.list[[1]], ALL.list[-1]) `


![image](https://github.com/samuel-marsh/scCustomize/assets/68268222/b866da33-2af5-46b1-b838-45a33f1ed96d)

**Comment by samuel-marsh** [comment]
Hi @levinhein,

So to answer your first question that unfortunately just seems like a memory issue.  You could try moving to a higher memory environment (HPC, cloud, etc) if that is available to you.  Alternatively you could explore Seurat/BPCells workflow and look into doing sketch based analysis.

In terms of meta data that should be fine and it should match things by column name I would think.  You can always test just using two of the objects that have different column orders and marge them and make sure that columns are handled appropriately.

Best,
Sam
