### ISSUE TITLE
Adding chicken to list of supported species?

### ISSUE THREAD

**Issue by dpearton** [samuel-marsh/scCustomize#176]
Hi,

Great package - I wish I'd found it before I had to laboriously make (inferior) versions of some of the iterative plot functions!

Would it be possible to add support for chicken (galgal7 or galgal6a) genomes?

Thanks.

**Comment by samuel-marsh** [comment]
Hi @dpearton,

Thanks for kind words!  Yes I think that should be possible.  I will update here when things are live in the dev branch.

Best,
Sam

**Comment by samuel-marsh** [comment]
Hi @dpearton,

Ok, Gallus gallus is now live in the develop branch v2.1.2.9036 or greater.  Simply provide any of the following for the `species` parameter: "Chicken", "chicken", "Gallus", "gallus", "Gg", or "Gg".

If you have any problems with the functions accepting chicken as species or correctly functioning please let me know and I will reopen the issue.

Best,
Sam
