### ISSUE TITLE
DotPlot_scCustom: Show Cluster Idents on top 

### ISSUE THREAD

**Issue by jakob-arnold** [samuel-marsh/scCustomize#181]
Hi Sam,

I generated a nice plot with the following code:

```
Clustered_DotPlot(vd1, features = top_markers,
  exp_color_middle=0, exp_color_min = -1, colors_use_idents=pal, k=8)
```
![image](https://github.com/samuel-marsh/scCustomize/assets/166120542/b382ab7f-c265-4086-8612-f4e2033a8868)

I would like to change the placement of the cluster labels, in this case that's only the cluster numbers (0-15). Is it possible to show these labels on the top, within the colored Identiy boxes (similar to setting `label=T, label.box = T` in `DimPlot_scCustom()`? In that case the Identity legend would be obsolete. Is there an easy way of doing this?

Thank you so much and kind regards
Jakob

**Comment by samuel-marsh** [comment]
Hi Jakob,

I’m so terribly sorry I thought I had responded to this issue when you posted it!

I will look into whether this is easily possible within the framework of complexHeatmap and see what I can do.

Sorry again!
Best,
Sam

**Comment by samuel-marsh** [comment]
So it looks like this is probably possible but unfortunately I don't currently have the bandwidth to implement and test this feature right now.  If you want to check out complexHeatmap documentation and figure it out I'm happy to entertain PR or you post code for me to check.

Thanks and sorry again,
Sam

**Comment by samuel-marsh** [comment]
Closing this for now but again if you have code or PR I'd more than happy to update.

Best,
Sam
