### ISSUE TITLE
Add_Mito_Ribo multiple species

### ISSUE THREAD

**Issue by rhart604** [samuel-marsh/scCustomize#184]
Hi and thanks for writing this incredibly valuable package!  I'm wondering if it would be possible to add an option to Add_Mito_Ribo to use multiple standard species?  I want to use both mouse and human.  Thanks!

**Comment by samuel-marsh** [comment]
Hi @rhart604,

Yes, that should be possible with some tweaks.  Just to clarify this is in case that you have dataset aligned to a combination genome both mouse and human in same dataset correct?

Best,
Sam

**Comment by rhart604** [comment]
Yes.  A standard 10X reference for a mixed mouse/human run uses "hg19-" and "mm10-" prefixes for gene symbols.

**Comment by samuel-marsh** [comment]
Hi @rhart604,

Ok this is now live in the release prep branch "release/2.2.0" (v2.1.2.9061 or greater).  To run use following (and replace `species_prefix` as needed):
```
OBJ <- Add_Mito_Ribo(object = OBJ, species = c("mouse", "human"), species_prefix = c("GRCm39-", "GRCh38-"))
```

Note: the order of `species` and `species_prefix` parameters MUST match or function will fail to find any features.

If you have any issues with the function after updating to in dev branch please let me know and I'll reopen the issue.

Best,
Sam
