### ISSUE TITLE
conversion to anndata

### ISSUE THREAD

**Issue by Flu09** [samuel-marsh/scCustomize#188]
Not sure what is the issue here

> as.anndata(x = obj2, file_path = "/tmp", file_name = "obj_anndata.h5ad")
• Checking Seurat object validity & Extracting Data
Warning: No layers found matching search pattern provided
Error in `as.anndata()`:
! `main_layer` must be one of counts
Run `rlang::last_trace()` to see where the error occurred.
> as.anndata(x = obj2,  file_name = "obj_anndata.h5ad")
Error in as.anndata.Seurat(x = obj2, file_name = "obj_anndata.h5ad") : 
  argument "file_path" is missing, with no default
> obj2
An object of class Seurat 
40090 features across 3600 samples within 1 assay 
Active assay: RNA (40090 features, 0 variable features)
 1 layer present: counts

**Comment by matosmr** [comment]
also having the same issue

**Comment by samuel-marsh** [comment]
Hi @Flu09 @matosmr 

Apologies for the delay responding!  Could you both try running the function using the following code and Seurat data package:
```
pbmc <- pbmc3k.SeuratData::pbmc3k.final
pbmc <- UpdateSeuratObject
```

Then run the conversion with identical code that is failing with your own objects (just swap out the object) in code.

Will help to figure out whether it is object or object format issue vs. function issue.

Thanks!
Sam

**Comment by joshuak94** [comment]
Hello Sam! Just wanted to say I'm having the same issue.

With the pbmc dataset it seems to work. The dataset where it doesn't work, however is the MOCA dataset (https://oncoscape.v3.sttrcancer.org/atlas.gs.washington.edu.mouse.rna/downloads)

Here is my code:
```r
library(Seurat)
library(scCustomize)

data = readRDS("~/gene_count_cleaned.RDS")
metadata = read.csv("/~cell_annotate.csv")

metadata_filtered = metadata[which(metadata$sample %in% colnames(data)), ]

data_seurat = CreateSeuratObject(data, meta.data = metadata_filtered)

as.anndata(x = data_seurat, file_path = "/project/MDL_JoshKim_Data/vista_sc_240706/moca/", file_name = "gene_count_cleaned.h5ad")
```

The error message:
```
• Checking Seurat object validity & Extracting Data
Warning message:
“No layers found matching search pattern provided”

Error in `as.anndata()`:
! `main_layer` must be one of counts
Traceback:

1. as.anndata(x = data_seurat, file_path = "[~/](http://localhost:8890/lab/tree/notebooks/moca/)", 
 .     file_name = "gene_count_cleaned.h5ad")
2. as.anndata.Seurat(x = data_seurat, file_path = "[~/](http://localhost:8890/lab/tree/notebooks/moca/)", 
 .     file_name = "gene_count_cleaned.h5ad")
3. cli_abort(message = "{.code main_layer} must be one of {.field {main_approved_slots}}")
4. rlang::abort(message, ..., call = call, use_cli_format = TRUE, 
 .     .frame = .frame)
5. signal_abort(cnd, .file)
```

Seurat version 5.1.0

**Comment by samuel-marsh** [comment]
Hi All (@Flu09 @marlmatos @joshuak94)

Sorry again for delays.  Could you all please try updating to dev release prep version:
```
devtools::install_github(repo = "samuel-marsh/scCustomize", ref = "release/2.2.0")
```

If that doesn’t solve the issue please let me know!

Best,
Sam

**Comment by samuel-marsh** [comment]
Hi All,

Just checking if updating to release branch fixed the issue?  I hope to push full release in next two weeks.

Thanks!
Sam

**Comment by joshuak94** [comment]
I've tried it with the updated version and I get the same error:

```
• Checking Seurat object validity
• Extracting Data from RNA assay to transfer to anndata.
Warning message:
“No layers found matching search pattern provided”

Error in `as.anndata()`:
! `main_layer` must be one of counts
Traceback:

1. as.anndata(x = data_seurat, file_path = "[./moca/](http://localhost:9999/lab/tree/notebooks/moca/)", 
 .     file_name = "gene_count_cleaned.h5ad")
2. as.anndata.Seurat(x = data_seurat, file_path = "[./moca/](http://localhost:9999/lab/tree/notebooks/moca/)", 
 .     file_name = "gene_count_cleaned.h5ad")
3. cli_abort(message = "{.code main_layer} must be one of {.field {main_approved_slots}}")
4. rlang::abort(message, ..., call = call, use_cli_format = TRUE, 
 .     .frame = .frame)
5. signal_abort(cnd, .file)
```

**Comment by joshuak94** [comment]
I'm a bit confused. I've run the installation a few times now:

`devtools::install_github(repo = "samuel-marsh/scCustomize", ref = "release/2.2.0", force = TRUE)`

And I see in the output:

```
✔  checking for file ‘/scratch/local/RtmpsDvbEh/remotes11ce41d3e0707/samuel-marsh-scCustomize-b702a1e/DESCRIPTION’ (395ms)
─  preparing ‘scCustomize’:
✔  checking DESCRIPTION meta-information
─  checking for LF line-endings in source and make files and shell scripts (855ms)
─  checking for empty or unneeded directories
─  building ‘scCustomize_2.1.2.9068.tar.gz’
```

So is the version 2.1.2.9086 the correct version?

**Comment by samuel-marsh** [comment]
Hi @joshuak94,

thanks for trying new version.  Yes that new version is correct, it’s the dev versioning as I prep for 2.2.0 release.  I will take a look at this more this week and get back to you here.

Best,
Sam

**Comment by joshuak94** [comment]
In the end, I managed to get it to work by normalizing the dataset before saving:

```R
library(Seurat)
library(scCustomize)

data = readRDS("/project/moca/gene_count_cleaned_sampled_100k.RDS")
metadata = read.csv("/project/moca/cell_annotate.csv")
metadata_filtered = metadata[which(metadata$sample %in% colnames(data)), ]
data_seurat = CreateSeuratObject(data, meta.data = metadata_filtered)
data_seurat = NormalizeData(data_seurat)

as.anndata(x = data_seurat, file_path = "/project/moca/", file_name = gene_count_cleaned_and_normalized_sampled_100k.h5ad")
```

I don't know if the h5ad format *requires* normalized data, but the source code I mentioned above seems like it requires a data layer in addition to the counts layer.

**Comment by samuel-marsh** [comment]
Hi @joshuak94,

Sorry had brain fog about this.  So that issue should be resolved if you set parameter `main_layer = "counts"` before running function.  It defaults to "data" but can be switched.

Best,
Sam

**Comment by joshuak94** [comment]
Ah I see! Well in the end, I just normalized the data and then exported to h5ad without an issue. 

Just wondering, when I load the h5ad file and inspect it this is the output:

```
AnnData object with n_obs × n_vars = 100000 × 26183
    obs: 'nCount_RNA', 'nFeature_RNA', 'sample', 'all_exon_count', 'all_intron_count', 'all_read_count', 'intergenic_rate', 'embryo_id', 'embryo_sex', 'nuclei_extraction_date', 'development_stage', 'Total_mRNAs', 'num_genes_expressed', 'Size_Factor', 'Main_Cluster', 'Main_cluster_tsne_1', 'Main_cluster_tsne_2', 'Sub_cluster', 'Sub_cluster_tsne_1', 'Sub_cluster_tsne_2', 'doublet_score', 'sub_cluster_id', 'Main_cell_type', 'Main_trajectory', 'Main_trajectory_umap_1', 'Main_trajectory_umap_2', 'Main_trajectory_umap_3', 'Main_trajectory_refined_by_cluster', 'Main_trajectory_refined_umap_1', 'Main_trajectory_refined_umap_2', 'Main_trajectory_refined_umap_3', 'Sub_trajectory_name', 'Sub_trajectory_umap_1', 'Sub_trajectory_umap_2', 'Sub_trajectory_louvain_component', 'Sub_trajectory_Pseudotime'
    layers: 'counts_RNA'
```

The counts_RNA layer is presumably the raw counts. Where would the normalized data go?

**Comment by samuel-marsh** [comment]
So in this layers: is showing any extra layers that are present.  Here is example converting object with counts and data and then one with just counts.

![image](https://github.com/user-attachments/assets/13fac02c-4ad9-4347-8047-5a5688764076)


Best,
Sam

**Comment by samuel-marsh** [comment]
@Flu09 @marlmatos 

Just checking if you two are still having issues?  If not I'll go ahead and close this issue for now.

Best,
Sam

**Comment by joshuak94** [comment]
Hi Sam! Quick question before you close it.

Does this mean that if I use main_layer = "counts", then my adata.X will store the raw count values? And if I use the default (main_layer = "data"), my adata.X stores the normalized values?

**Comment by samuel-marsh** [comment]
Yes that is correct.  What lever is specified as main_layer goes there and if other layers are specified they go in as extra layers in anndata object.

Best,
Sam

**Comment by ohmstead** [comment]
Hi there, it seems it is not possible to export a Seurat object with only a "counts" layer to anndata.
```
> nuclei
An object of class Seurat 
57010 features across 16988 samples within 1 assay 
Active assay: RNA (57010 features, 0 variable features)
 1 layer present: counts

> as.anndata(x = nuclei, file_path = save_dir, file_name = "nuclei_MapMyCells.h5Seurat", main_layer = "counts")
• Checking Seurat object validity & Extracting Data
Error in `as.anndata()`:
! `main_layer` and `other_layers` cannot overlap.
Run `rlang::last_trace()` to see where the error occurred.

> as.anndata(x = nuclei, file_path = save_dir, file_name = "nuclei_MapMyCells.h5Seurat", main_layer = "counts", other_layers = "")
• Checking Seurat object validity & Extracting Data
Error in `as.anndata()`:
! One or more of were not found in Seurat object.
Run `rlang::last_trace()` to see where the error occurred.

> as.anndata(x = nuclei, file_path = save_dir, file_name = "nuclei_MapMyCells.h5Seurat", main_layer = "counts", other_layers = "data")
• Checking Seurat object validity & Extracting Data
Error in `as.anndata()`:
! One or more of data were not found in Seurat object.
Run `rlang::last_trace()` to see where the error occurred.

> as.anndata(x = nuclei, file_path = save_dir, file_name = "nuclei_MapMyCells.h5Seurat", main_layer = "counts", other_layers = NA)
• Checking Seurat object validity & Extracting Data
Error in `as.anndata()`:
! One or more of NA were not found in Seurat object.
```

**Comment by samuel-marsh** [comment]
Hi @ohmstead,

if you set other layer to `NULL` it will allow you to create object with just counts layer.

To make sure everything works correctly please update to release version:
```
devtools::install_github(“samuel-marsh/scCustomize”, ref = “release/3.0.0”)
```

Best,
Sam

**Comment by ohmstead** [comment]
@samuel-marsh That worked perfectly, thank you!
