### ISSUE TITLE
Clarification regarding `exp_value_type = "scaled"` in `scCustomize::Clustered_DotPlot`

### ISSUE THREAD

**Issue by denvercal1234GitHub** [samuel-marsh/scCustomize#196]
Hi Sam, 

Thanks again for a great tool. 

I was a bit unclear regarding the scaling in this plot. With the below parameters, I would have thought that since the `split.by=NULL`, the `exp_value_type="scaled"` would just be ignored. But, why setting `exp_color_min = 0, exp_color_max = 5` still make the expression range go from 0? I am confused which data transformation is actually being plotted here? 

Thank you for your help. 

```
scCustomize::Clustered_DotPlot(seurat_object = PBMC_MERGED, features = unique(c(curated_P14P15_signifPosDEGs)), k=7, plot_km_elbow=F, print_exp_quantiles=T, exp_color_min = 0, exp_color_max = 5, cluster_feature=T, cluster_ident=T, assay = "SCT", group.by = "Tissue_Cell_Leiden_clusterID_short", column_label_size = 5, exp_value_type = "scaled", split.by = NULL)
```

```
Quantiles of gene expression data are:       10%        50%        90%        99% 
-0.7443979 -0.2946256  1.2836032  4.2965102 
```

**Comment by samuel-marsh** [comment]
Hi @denvercal1234GitHub,

Sorry for delay getting back to you.  So the exp color parameters are simply modifying the scale that is displayed and not the underlying data.  So when you set those values on scaled data any values normally less than 0 just get set to the 0 on the scale so you are just creating a misleading visualization.  I recommend keeping those parameters at defaults or only slightly modifying based on data plotted to avoid this issue.

Best,
Sam
