### ISSUE TITLE
"reduction" argument missing on "Cluster Highlight Plot" man page

### ISSUE THREAD

**Issue by jasonleongbio** [samuel-marsh/scCustomize#198]
Dear Sam,

Thank you so much for your ongoing effort to improve this package for generating beautiful plots. 
Recently I have been using the `Cluster_Highlight_Plot()` function quite a lot to visualize my data on different embeddings and it really helped me a lot. 
- Initially I thought the function can only be used to generate "umap" plot because by following the code in the examples, it always returned a UMAP plot to me.
- But then I realized that by specifying `reduction = "other_reduction_name"`, it can actually be used to visualize the other embeddings as well.
- Therefore, I think it would be useful to add the `reduction` argument to the man page of the function so that how this is used can be clarified. Meanwhile, what the default option for the `reduction` argument is actually not clearly stated so users may be confused by what is actually visualized without setting this in the `Cluster_Highlight_Plot()` function.

Hope this will help clarify the behavior of this function.

Best regards,
Jason Leong

**Comment by samuel-marsh** [comment]
Hi Jason,

Thanks for the kind words and for submitting the issue.  Yes as you found any of the parameters from `Seurat::DimPlot` can be passed to the function (see entry for `...` in manual.  However, I do agree in this case reduction should be explicitly include in the scCustomize function parameter options.  I have just update this in the release dev version (v2.1.2.9070 or greater).  If you have any issues after updating to that branch please let me know and I'll reopen the issue.

Best,
Sam
