### ISSUE TITLE
as.anndata raises error in which(): argument to which () is not logical

### ISSUE THREAD

**Issue by tjm-sci** [samuel-marsh/scCustomize#207]
Hi, I've been grappling with the [Allen Mouse Cortex](https://portal.brain-map.org/atlases-and-data/rnaseq/mouse-whole-cortex-and-hippocampus-10x) data and have created a seurat object from it containing 10K cells. I'm trying to convert it to an Anndata object and originally was getting the main_layer error discussed in #188. After adding the `main_layer = "counts". other_layers = NULL` arhuments i'm getting a new error:  
`> allen_10k_sr
An object of class Seurat 
31053 features across 10000 samples within 1 assay 
Active assay: RNA (31053 features, 0 variable features)
 1 layer present: counts
> as.anndata(x = allen_10k_sr, file_path = "RDS_objects/", file_name = "allen_10k", main_layer = "counts", other_layers = NULL)
• Checking Seurat object validity & Extracting Data
The following columns were removed as they contain identical values for all rows:
ℹ orig.ident, platform_label, facs_population_plan_label, injection_roi_label,
  injection_materials_label, injection_method_label, injection_type_label,
  facs_population_plan_id, facs_population_plan_color, injection_materials_id,
  injection_materials_color, injection_method_id, injection_method_color, injection_roi_id,
  injection_roi_color, injection_type_id, injection_type_color, cell_type_alt_alias_label,
  …, cortical_layer_order, and cortical_layer_color
Error in `select()`:
ℹ In argument: `which(single_val_columns)`.
Caused by error in `which()`:
! argument to 'which' is not logical
Run `rlang::last_trace()` to see where the error occurred.`

If you want to take a look with the seurat object you can download it  [here](https://www.dropbox.com/scl/fi/o91hbhapt767rzln9u9mt/allen_10k.rds?rlkey=vr3ohtfoyf2vl31db3peq61ak&st=tezezdmx&dl=0), any help is greatly appreciated

**Comment by samuel-marsh** [comment]
Hi @tjm-sci,

Sorry this is a bug in the current release.  It is fixed if you updated to soon to be released version:

```
devtools::install_github("samuel-marsh/scCustomize", ref = "release/3.0.0")
```

If the issue persists after update please let me know and I’ll reopen the issue.

Best,
Sam

**Comment by tjm-sci** [comment]
Hi @samuel-marsh , that's done the trick. many thanks!

**Comment by pessoapereira** [comment]
Hi @samuel-marsh. Thanks so much for your amazing work!

I have updated to the 3.0.0 version but am still dealing with warning errors. Am I missing something?

>cells_subclusters 
An object of class Seurat  
50103 features across 43386 samples within 3 assays  
Active assay: SCT (21335 features, 0 variable features)  
3 layers present: counts, data, scale.data  
2 other assays present: RNA, integrated 
3 dimensional reductions calculated: pca, umap, tsne
--
 
as.anndata(x = cells_subclusters, file_path = "D:/R01/sc_RNAseq/", file_name = "sub_anndata.h5ad", assay = "SCT", main_layer = "data", transer_dimreduc = TRUE, verbose = TRUE)
• Checking Seurat object validity
• Extracting Data from SCT assay to transfer to anndata.
• Creating anndata object.
Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  ValueError: Value passed for key 'counts_SCT' is of incorrect shape. Values of layers must match dimensions ('obs', 'var') of parent. Value had shape (43386, 18219) while it should have had (43386, 21335).
Run `reticulate::py_last_error()` for details.
In addition: Warning messages:
1: Adding a command log without an assay associated with it 
2: Adding a command log without an assay associated with it 
3: Adding a command log without an assay associated with it 
4: Adding a command log without an assay associated with it 

Thanks much again! Any help would be greatly appreciated.
