### ISSUE TITLE
Option to change dot size in Clustered_DotPlot()?

### ISSUE THREAD

**Issue by reyancoskun** [samuel-marsh/scCustomize#211]
Is there the option to change the dot size in Clustered_DotPlot() like in the Seurat DotPlot() function with dot.scale?

Thanks!

**Comment by samuel-marsh** [comment]
Hi,

There is currently not option to adjust this and unfortunately my current bandwidth is unlikely to allow for me to work on this for while.  If you want to submit PR or even just code to review, I would be happy to take a look and merge.

Thanks!
Sam
