### ISSUE TITLE
SCTAssay Convert to Assay5

### ISSUE THREAD

**Issue by Shuozhen** [samuel-marsh/scCustomize#219]
Thank you for the wonderful package, it saves a lot of trouble to convert the assays from older versions to the Seurat v5. One minor feature I would suggest is to convert SCTAssay to Assay5. Currently it does not seem to be supported by the function Convert_Assay(). It's easy to realize with seurat_obj[["SCT"]] <- as(seurat_obj[["SCT"]], "Assay5")  so it would be wonderful to have this function integrated with the Convert_Assay() function. Thank you again for your nice package!!

**Comment by samuel-marsh** [comment]
Hi @Shuozhen,

Thanks for kind words!  So unfortunately this is not possible because SCTAssay is separate class in Seurat.  It is neither Assay nor Assay5 but its own class and converting it can cause downstream issues in functionality.

Best,
Sam
