### ISSUE TITLE
SingleCellExperiment support

### ISSUE THREAD

**Issue by MarcElosua** [samuel-marsh/scCustomize#26]
Hi @samuel-marsh 

Thank you so much for developing such a great toolkit to analyze single cell data. I have recently moved from Seurat to bioconductor's SingleCellExperiment to analyze my sc data. While using Seurat I regularly used scCustomize and I was wondering if it is in the books to make scCustomize compatible with SingleCellExperiment objects. 

Again, thank you so much for developing such an amazing package!

**Comment by samuel-marsh** [comment]
Hey @MarcElosua,

Sorry for delay getting back to you and thanks so much for kind words!!  I would love to make things compatible with SCE framework and learning object structure and things of SCE has been on my to do list for while.  Unfortunately, in short term (at least on my end) it's not on immediate horizon.  I'd be more than happy to entertain any PRs for modifying existing functions to work with SCE too or to add specifc SCE versions of functions or discuss how things could be adapted to that framework.  Hope I can work on some of it too in future but again unfortunately just not in cards in short term.

Thanks!
Sam
