### ISSUE TITLE
Integration of different species datasets

### ISSUE THREAD

**Issue by giorgiatosoni** [samuel-marsh/scCustomize#28]
Thank you for this amazing tool!

- [ ] Would it be possible to add a feature to convert gene names in the corresponding orthologs, for integration across different species?
- [ ] Would it be possible to add 'Features Mito/Ribo Functions' for macaca mulatta?

**Comment by samuel-marsh** [comment]
Hi @giorgiatosoni macaca mulatta is now live in both the Seurat and LIGER mito functions.  Dev branch (v0.7.0.0015).  Let me know if you run into any issues.

See:
```
Add_Mito_Ribo_Seurat(list_species_names = T)

  Mouse_Options Human_Options Marmoset_Options Zebrafish_Options Rat_Options Drosophila_Options Macaque_Options
1         Mouse         Human         Marmoset         Zebrafish         Rat         Drosophila         Macaque
2         mouse         human         marmoset         zebrafish         rat         drosophila         macaque
3            Ms            Hu               CJ                DR          RN                 DM          Rhesus
4            ms            hu               Cj                Dr          Rn                 Dm          macaca
5            Mm            Hs               cj                dr          rn                 dm        mmulatta
6            mm            hs             <NA>              <NA>        <NA>               <NA>            <NA>
```


I'm going to close issue for now but know that gene conversion is something that I'm thinking about and if/when I figure out a way I like to do it then I'll ping you here.

Best!
Sam

**Comment by giorgiatosoni** [comment]
<img width="847" alt="image" src="https://user-images.githubusercontent.com/94447264/159229579-153db15b-1d7b-4dad-a0d0-0c4fbed67c82.png">

Hi,

I still don't see the macaque options..

Best,

Giorgia

**Comment by samuel-marsh** [comment]
Hi Giorgia,

Did you install off of the develop branch?  What is result of:
```
packageVersion("scCustomize")
```

Best,
Sam

**Comment by giorgiatosoni** [comment]
> Hi Giorgia,
> 
> Did you install off of the develop branch? What is result of:
> 
> ```
> packageVersion("scCustomize")
> ```
> 
> Best, Sam

> packageVersion("scCustomize")
[1] ‘0.7.0’

**Comment by samuel-marsh** [comment]
oh yes need to install off the develop branch until I move this onto a new release.

In new R session run:
```
devtools::install_github("samuel-marsh/scCustomize", ref = "develop")
```

Best,
Sam

**Comment by denvercal1234GitHub** [comment]
Hi @samuel-marsh thanks for recommending the `orthogene` package. However, it relies on the `grr` package which is no longer on CRAN. Do you know a good alternative to search ortholog of genes between mouse and humans? `biomaRt` is facing issues too at the moment (https://github.com/Huber-group-EMBL/biomaRt/issues/152). Thank you.

**Comment by samuel-marsh** [comment]
Hi @denvercal1234GitHub,

I have just created an issue over on orthogene GitHub in case they aren't aware.  Skene lab/Brian are usually pretty responsive devs so hopefully they have fix soon (or grr is fixed, but possible it might be orphaned as last update to grr was 9 years ago).  Until then orthogene should continue to work just fine if you install grr from CRAN archive first before installing orthogene.  biomaRt issue seems like it's mostly with new release so setting to older release should be ok.

If it's between mouse and human orthologs then could also use resources from MGI and do conversion manually, more work but potential work around for now. https://www.informatics.jax.org/downloads/reports/index.html

Best,
Sam
