### ISSUE TITLE
Stacked_VlnPlot change labels

### ISSUE THREAD

**Issue by sparsepix** [samuel-marsh/scCustomize#36]
Hi,

I am using a Seurat object with EnsIDs as rownames. Unfortunately, Seurat is very bad at handling gene-level metadata. I can put the symbols and other information about each feature manually in the gene level metadata slot, but all of the Seurat functions lack an option to retrieve them upon plotting. Therefore I have to manually change the labels of each plot by `scale_x_discrete(labels = df$symbols) `. This works fine for DotPlots and I managed to write a function for multiple-feature plots as well. But I can't get it to work with stacked VlnPlots (as these are technically multiple wrapped plots, I assume?) 

Would be great if there was a feature to supply alternative feature names to Stacked_VlnPlot. Of course, this would be very handy for all other enhanced scCustomize plotting functions, too. Maybe even with an option to just specify the slot in the feature level metadata that is to be used for plotting instead of `rownames()`

Thanks a lot for your help,
best Niko

**Comment by samuel-marsh** [comment]
Hi Niko,

No problem!  Ya I haven't been following the back and forth on whether it will be supported but if it is in the future I will definitely add support here as well.  

Best,
Sam
