### ISSUE TITLE
Fixing levels of grouping variables when splitting DimPlots

### ISSUE THREAD

**Issue by sparsepix** [samuel-marsh/scCustomize#37]
Hey,
sorry for already another feature request, but here it comes: When splitting DimPlots using `split.by` the number of levels of the grouping variable for `group.by` gets reduced to only the levels that are actually in the cells being plotted in every split. This is very distracting for example when u split a clustering result over many subplots and the colors for the clusters change in every subplot due to some of the clusters being specific for one of the covariates split by. 

Thanks a lot,
Niko

**Comment by samuel-marsh** [comment]
Hi Niko,

no worries!  Just to clarify does this also occur with Seurat::DimPlot or just when using DimPlot_scCustom?

Thanks,
Sam

**Comment by sparsepix** [comment]
Happens in Seurat as well :(

**Comment by samuel-marsh** [comment]
Ok let me take look at DimPlot code in Seurat and see if there is fix.  Not remembering how the split is implemented there but I feel like this should be addressable.

**Comment by sparsepix** [comment]
Yes, exactly the problem I was describing. And sorry, you were right Seurat handles this fine. Thanks so much already :)

**Comment by samuel-marsh** [comment]
Ok ya no worries.  I will work on fix for DimPlot_scCustom.  I *think* it should be relatively easy by just creating additional variable that subsets the color list per plot being created.

Best,
Sam

**Comment by samuel-marsh** [comment]
ok so that solution did work (ish) but there is far easier one just setting manual scale using named vector.  Should be fixed now in the develop branch v0.7.0.9912.  If bug still occurs for you with this update let me know and I'll reopen the issue.

Best,
Sam
