### ISSUE TITLE
Color legends for VlnPlot and Stacked_VlnPlot

### ISSUE THREAD

**Issue by sparsepix** [samuel-marsh/scCustomize#48]
Hi,
I think this is a known issue, but would it be possible to add functionality for labeling the colors when using split.by in VlnPlots or Stacked_VlnPlots? 

Best,
Niko

**Comment by samuel-marsh** [comment]
Hi Niko,

Can you provide example of the issue you are describing?

Best,
Sam

**Comment by sparsepix** [comment]
Hey Sam,
sorry I didn't attach one as I saw you were commenting on the same issue over at the Seurat GitHub explaining that their Function doesn't support this. Here you go with the mwe and resulting plots:

`
library(Seurat)
library(scCustomize)
library(tidyverse)
data("pbmc_small")
pbmc_small %>% VlnPlot_scCustom(features = rownames(pbmc_small)[1:10])
pbmc_small %>% Stacked_VlnPlot(features = rownames(pbmc_small)[1:10])
`
![ce973b93-e523-4b86-96d7-e7666046c00a](https://user-images.githubusercontent.com/26229719/179222981-343b2c65-14be-4fd9-ba19-0c5ca5fb3ebb.png)
![c4aa0213-2343-4522-ac56-e024e269202b](https://user-images.githubusercontent.com/26229719/179222990-535a544d-1fa8-47e4-a25f-59e221150f1c.png)

**Comment by sparsepix** [comment]
Hey,
sorry I messed the example up and forgot the` split.by = 'groups'` option.
What I actually meant was:

```library(Seurat)
library(scCustomize)
library(tidyverse)
library(patchwork)

data("pbmc_small")
p = list()
p[[1]] = pbmc_small %>% VlnPlot_scCustom(features = rownames(pbmc_small)[1:4],split.by = 'groups') + theme(legend.position = 'bottom')
p[[2]] = pbmc_small %>% VlnPlot_scCustom(features = rownames(pbmc_small)[1:4],split.by = 'groups') & theme(legend.position = 'bottom') 
p[[3]] = pbmc_small %>% Stacked_VlnPlot(features = rownames(pbmc_small)[1:4],split.by = 'groups') + theme(legend.position = 'bottom')
p[[4]] = pbmc_small %>% Stacked_VlnPlot(features = rownames(pbmc_small)[1:4],split.by = 'groups') & theme(legend.position = 'bottom')

wrap_plots(p)```

Here we can see that & works to add the legend in both cases, but + only works for VlnPlot and not for Stacked. 

Originally I thought it also doesn't work with VlnPlot_scCustom, but this was a problem with patchwork and parentheses as I've just realized. Sorry for that. 
![6db53be2-f45b-4bf6-94b4-266b30010ea2](https://user-images.githubusercontent.com/26229719/179225774-9148c262-a367-41da-a9df-e3d354854f44.png)

**Comment by samuel-marsh** [comment]
Hi,

So fix for this is now live in the develop branch v0.7.09926.  I chose to solve the issue by adding extra parameter to the function.  You can now use `plot_legend = TRUE` in order to display a single legend so stacked vlnplots.

This parameter is still compatible with ggplot/patchwork theming in order to move/edit legend.

If you run into any issues getting this work please let me know and I'll reopen the issue.

Best,
Sam


```
library(tidyverse)
library(Seurat)
library(scCustomize)

pbmc <- pbmc3k.SeuratData::pbmc3k.final
pbmc <- UpdateSeuratObject(pbmc)

Stacked_VlnPlot(pbmc, c("FOS", "CD3E"), plot_legend = TRUE)

Stacked_VlnPlot(pbmc, c("FOS", "CD3E"), plot_legend = TRUE) & theme(legend.position = "bottom")
```

![image](https://user-images.githubusercontent.com/38284410/181260551-e0624973-2175-4070-a91e-8ed8060be21d.png)

![image](https://user-images.githubusercontent.com/38284410/181260606-c1a2e4f4-8a01-490c-a2f8-085890907c44.png)
