### ISSUE TITLE
move ggrastr to Suggests

### ISSUE THREAD

**Issue by cstubben** [samuel-marsh/scCustomize#52]
Can you move ggrastr from imports to suggests?  ggrastr requires Cairo which was cool 15 years ago and now is just a pain to install.

**Comment by samuel-marsh** [comment]
Hi,

Can you clarify what issue you are having with the Cairo dependency from ggrastr?  

This is something I can think about solutions for but overall the philosophy of package is to simplify things for the end user.  The default raster of VlnPlots with increasing large datasets provides significant end user advantages.

Best,
Sam

**Comment by samuel-marsh** [comment]
I will be working on this with ggrastr devs to make Cairo dependency optional for ggrastr.  It will take little time for that plus ggrastr update so please let me know if I can help with your Cairo issue in meantime.

**Comment by cstubben** [comment]
install.packages("Cairo") returns "xlib-backend.c:34:10: fatal error: 'X11/Intrinsic.h' file not found" on my Mac M1 laptop.  I'm not even sure if homebrew install R supports Cairo by default anymore, so I just installed scCustomize by deleting  ggrastr from the DESCRIPTION file.

**Comment by samuel-marsh** [comment]
So in your specific case it appears that this may solve issue:
https://stackoverflow.com/a/66568545

I checked and both libxt and Cairo home brew packages are compatible with new M1/M2 chips.
https://formulae.brew.sh/formula/libxt
https://formulae.brew.sh/formula/cairo

Regardless as I mentioned I’m gonna submit PR to ggrastr that will change the explicit depends so in future won’t be issue.

Hope scCustomize is useful for you and let me know if you run into any other issues.

Best,
Sam
