### ISSUE TITLE
Plot_Density_Custom custom_palette option only applies the custom palette to last plot if passed multiple genes

### ISSUE THREAD

**Issue by jdparker101** [samuel-marsh/scCustomize#53]
Hi, first of all, thanks for making the excellent package, it has been extremely helpful. However, I have a suggestion for an improvement. You can pass multiple genes to the nebulosa function plot_density and likewise your custom function that uses plot_density, Plot_Custom_Density in order to make a nice figure panel of nebulosa figures. However, when you pass multiple genes to Plot_Custom_Density with the custom_palette option set to your own bespoke color scheme, the colors are only applied to the last plot. Perhaps there is a way around this to get it to apply to all the plots I am not aware of, but if not, it would be a helpful amendment.

**Comment by samuel-marsh** [comment]
Hi,

Thanks for kind words!!  That’s good catch.  I’ll take look over weekend but believe it’s simple fix and I can push fix early next week to the develop branch.

Thanks!
Sam

**Comment by samuel-marsh** [comment]
Hi,

Sorry for the delay here.  The fix is now available of the develop branch v0.7.0.9934.  If you run into any issues still please comment here and I'll reopen issue.

Best,
Sam
