### ISSUE TITLE
Any way to change legend order?

### ISSUE THREAD

**Issue by SimoniMD** [samuel-marsh/scCustomize#55]
So I have a UMAP that assigns colors based on cell size, and then I used scCustomize to make a clustered dotplot. However, i notice that the clustered Dotplot order is alphabetical. Any way to make it a custom order (but keep the associated colors), so that i can match my legends? I feel like I can do this in photoshop, but it would be tedious. I read in another thread that the clustered dotplot isn't ggplot? so not sure how to approach it.

I'm trying to match this order from my umap (made with dittoseq):
<img width="28" alt="image" src="https://user-images.githubusercontent.com/82599359/185701242-778a6843-c26a-4af5-a8cf-357413ad773d.png">

with this from the dotplot:
<img width="55" alt="image" src="https://user-images.githubusercontent.com/82599359/185701138-ddca8c88-7a9d-48e9-bbf3-9ce0360ca700.png">

Thanks!

**Comment by samuel-marsh** [comment]
Hi @SimoniMD,

Sorry for delay getting to this.  I have added fix in the develop branch v0.7.0.9935.  `Clustered_DotPlot` now returns the legend using the factor levels from the active.ident in Seurat object.  You can easily change the resulting plot by re-leveling the object.

If you run into any issues, let me know and I can reopen the issue.

Best,
Sam
