### ISSUE TITLE
Are cell numbers normalized?

### ISSUE THREAD

**Issue by singcell** [samuel-marsh/scCustomize#56]
I wanted to determine if the number of particular cell type in a cluster is changing with the treatment conditions. I have used stimulated vs. control PBMC datasets Seurat vignette for this analysis comparing two conditions.

Question:
I used the code below to get the counts in each cluster and treatment condition. I wanted to know if number of cells from the code below is normalized to the total number of cells sequenced for each samples.

`table(Idents(immune.combined), immune.combined$stim)`

Does the output of number of  cells from scCustomize  is normalized to the total number of cells sequenced for each samples? if the cell numbers are not normalized then what scCustomize function should I use?

Thank you.

**Comment by samuel-marsh** [comment]
Hi,

As found in the documentation for the `table` function just returns counts:  
```
table uses the cross-classifying factors to build a contingency table of the counts at each combination of factor levels.
```

What output are you referring to in scCustomize with regards to counts of cells?  `Cluster_Stats_All_Samples`?

In terms of quantifying abundance changes in single cell sequencing you should use packages/statistical models that are specifically designed to test for those changes and not simply comparing counts or normalized counts using typical statistical tests (i.e. t-test).  I typically use MASC for my scRNA-seq abundance change analysis but there are others as well including cluster independent methods like CNA or milo.

Best,
Sam

**Comment by samuel-marsh** [comment]
Hi,

As you haven’t heard back I’m going to close this issue.  If you are still interested/have issues please comment here and I can reopen the issue or start a new issue.

Best,
Sam
