### ISSUE TITLE
meta_sample_list_test' not found

### ISSUE THREAD

**Issue by dacheampong** [samuel-marsh/scCustomize#57]
Hello, I do get this error "meta_sample_list_test' not found"  any time I set these two features to (feature 1= nCount_RNA & feature2 = nFeature_RNA). It did work for me after changing it to meta_sample_list. Thanks

r command:
Split_FeatureScatter(seurat_object =  data_raw_control_seurat_obj, feature1 = "nFeature_RNA", 
                      feature2 = "nCount_RNA", pt.size=0.1, split.by = "orig.ident", colors_use = "red")

error message: 
Error in lapply(1:length(x = meta_sample_list_test), function(i) { : 
  object 'meta_sample_list_test' not found

**Comment by samuel-marsh** [comment]
Hi,

Sorry about that, it’s my bad, but of test code not changed.  I’ll push a fix later tonight and update here when done.

Best,
Sam

**Comment by samuel-marsh** [comment]
Hi,

Thanks again for pointing out the issue.  I've the error code and pushed update to develop branch (v0.7.0.9936).  If you run into any other issues with function related to this please let me know here and I'll reopen the issue.

Best,
Sam
