### ISSUE TITLE
Stacked_VlnPlot + Legend

### ISSUE THREAD

**Issue by teresa-swift** [samuel-marsh/scCustomize#63]
Hi, thank you for such a great visualisation tool!

Just wondering if when using Stacked_VlnPlot with a split.by argument, is there a way to display a legend? For example if using the standard Seurat VlnPlot a legend appears by default. 

Apologies for a rather basic question I'm not that familiar with R. 

Currently running something like this with no legend. Hoping for the same output but with "black = unstim, grey = stim", assuming my orig.ident is stim/unstim.

Stacked_VlnPlot(s_object, features = c("CD4","PTPRC"), split.by = "orig.ident"). 

Thank you for any help!

![example_plot](https://user-images.githubusercontent.com/93649768/196177070-6383ef5c-5c48-4389-81bd-d2c97a6f6d83.png)

**Comment by samuel-marsh** [comment]
Hi,

Thanks so much for the kind words!  Yes, there is an optional parameter in `Stacked_VlnPlot` called `plot_legend` that works with both unsplit and split plots.  See here for example of using with unsplit plots: https://github.com/samuel-marsh/scCustomize/issues/48#issuecomment-1196775427

And here is example with split plots:

```
library(tidyverse)
library(Seurat)
library(scCustomize)
library(patchwork)

pbmc <- pbmc3k.SeuratData::pbmc3k.final
pbmc <- UpdateSeuratObject(pbmc)

# add psuedo groups
pbmc$sample_id <- sample(c("sample1", "sample2"), size = ncol(pbmc), replace = TRUE)

# Plot with legend
Stacked_VlnPlot(pbmc, c("FOS", "CD3E"), split.by = "sample_id", plot_legend = TRUE)

# Can change legend location with standard theming
Stacked_VlnPlot(pbmc, c("FOS", "CD3E"), split.by = "sample_id", plot_legend = T) & theme(legend.position = "bottom")
```

![image](https://user-images.githubusercontent.com/38284410/196198731-8401c34b-fe05-4c72-b97f-46966a629edb.png)
![image](https://user-images.githubusercontent.com/38284410/196198771-ed933387-bfe2-410d-b898-f108c4758935.png)

If you have any issues let me know and I'll reopen the issue!

Best,
Sam
