### ISSUE TITLE
adding metadata after reading multipal files

### ISSUE THREAD

**Issue by amoyguang1** [samuel-marsh/scCustomize#88]
Dear Dr. Marsh,
 
Your scCustomize package is very cool. I am a postdoc and learning scRNA-Seq in R. May I ask you some questions related to it, please?
 
I used this code to make a dataset (pbmc_10X <- Read10X_h5_GEO(data_dir = "C:/Users/.../Documents/data/scRNA/PBMC"). It returned an object with all different samples, which was in .h5 format for individual sample.
 
May I ask how to add metadata into it (like sample group, time point, etc.)? And how to convert this file into singlecellexperiment data format? And in python, cell id is change by this code, adata.obs_names = [str(sample)+'_'+str(j).split('-')[0] for j in adata.obs_names]. How to do this in R?
 
Thanks a lot

**Comment by samuel-marsh** [comment]
Hi @amoyguang1,

I'm so sorry for delay getting back to you on this issue!  Have you solved this issue or do you still need help?

Thanks!
Sam

**Comment by amoyguang1** [comment]
Hi Sam. I have it solved. Thank you.

**Comment by samuel-marsh** [comment]
Great!!
