### ISSUE TITLE
Parameter 'raster' of function 'QC_Plots_Feature' is not passed to 'VlnPlot'

### ISSUE THREAD

**Issue by YukuanHuang** [samuel-marsh/scCustomize#91]
```r
# insert reproducible example here
```

<details>
  <summary> sessionInfo() output</summary>
  
```r
PASTE HERE sessionInfo() output
```
  
</details>

**Comment by samuel-marsh** [comment]
Hi,

Thanks for bug report.  I’ve also spotted another bug in that function.  I’ll push fix on the develop branch tomorrow.  I’ll update here when it’s all set.

Thanks,
Sam

**Comment by samuel-marsh** [comment]
Ok should be all set now in develop branch v1.1.1.9002.  If you still have issues please let me know and I'll reopen the issue.

Best,
Sam

**Comment by samuel-marsh** [comment]
Actually make it 1.1.1.9003.  Introduced another bug by accident.
