### ISSUE TITLE
CellBender dual assay object

### ISSUE THREAD

**Issue by giorgiatosoni** [samuel-marsh/scCustomize#92]
Hi,

I'm using the Create_CellBender_Merged_Seurat() to create a dual object, however it is not very clear to me which cells are kept when creating the object. In the vignette is reported that "we assume that we will use the cell calling algorithm of Cell Ranger with the modified counts for Cell Bender". 
The Cell Ranger matrix I'm using is 36601x14100
The Cell Bender matrix is 36601x3042351

The dual seurat object has 10689 cells. Where is this number coming from?

Thank you in advance!

Giorgia

**Comment by samuel-marsh** [comment]
Hi Giorgia,

That’s a little strange, let me look into that.  To be honest wrote that function while ago and haven’t touched in a while and it could do with some better parameters to customize object creation too.  I’ll take look at  that issue and get back to you.

Best,
Sam

**Comment by giorgiatosoni** [comment]
Hi, 
No problem and thanks for getting back to me!
I forgot to update this, but indeed I discovered that the difference in the number of cells is due to the min.features parameter.

Best,

Giorgia

**Comment by samuel-marsh** [comment]
Great!!  Glad it worked out!

Best,
Sam
