### ISSUE TITLE
Additional features to implement

### ISSUE THREAD

**Issue by kasumaz** [samuel-marsh/scCustomize#95]
Hi, Just an idea: I use seurat (and now also sc customize) and sometimes also DESEQ2 for bulk experiments. I often have to find time to connect the gene lists that come out of a differential expression analysis to additional tools like clusterprofiler to then do some pathway/GO analysis. It would be handy to be able to do this without setting up further code and maybe even store this information within seurat/DESEQ2 objects. Thanks.

**Comment by samuel-marsh** [comment]
Hi,

Can you better explain what you mean by connect the gene lists?  What are you thinking new function would do specifically?

thanks!
Sam

**Comment by kasumaz** [comment]
What I mean, if there was a way to perform gene ontology/pathway analysis right from the gene lists produced. I could do this myself via using clusterprofiler, but others may not be able to. This sort of follow-up analysis is always missing from single cell analysis tools.
