### ISSUE TITLE
Adjust size x-axis labels (col_label_size)

### ISSUE THREAD

**Issue by massonix** [samuel-marsh/scCustomize#96]
Hey Sam,

Thanks once more for developing this very useful package! Here's a plot I generated with the following code:

```
Clustered_DotPlot(
  seurat,
  features = pos_genes,
  colors_use_exp = viridis::inferno(20),
  colors_use_idents = cols_annotation,
  row_label_size = 6,
  plot_km_elbow = FALSE,flip = TRUE
)
```

![image](https://user-images.githubusercontent.com/35916509/226569955-3592b0fa-2306-4b15-81e8-fe8120143876.png)

As you can see, I could adjust the size of the cluster labels (rows), but I would also like to adjust the size of the column labels (features), as well as the size of the legend text. Would it be possible to add two additional parameters to do so? 

Thanks!

Ramon

**Comment by samuel-marsh** [comment]
Hey Ramon,

Thanks so much (and congrats on your Ph.D. defense!).  Yes I agree I think those parameters should be added.  The column labels are easy and the legend font size should totally be possible but will have to do little extra testing there to make sure that all of the legend components get modified correctly.  I'll update here when it's ready.

Best,
Sam

**Comment by massonix** [comment]
Thanks Sam, I truly appreciate this!

Ramon

**Comment by samuel-marsh** [comment]
No problem!  Judt update will probably be next week.  I have the column labels and 2 of 3 legend components and their titles working.  Just gotta get third to follow suit.  At conference rest of week but will get it pushed next week.

Best,
Sam

**Comment by samuel-marsh** [comment]
Ok actually easy fix so we are up and running on the develop branch (v1.1.1.9007).  There are 3 new parameters:
- `column_label_size` to change the column labels
- `legend_label_size` to change the labels of the legend guides
- `legend_title_size` to change size to guide titles.

If any of these doesn't work for you or if there are other changes you think would be helpful just let me know!  I'll close issue for now but will reopen if there are any continued bugs once you test it out.

Best,
Sam

**Comment by massonix** [comment]
thanks so much! I will try it out soon

**Comment by massonix** [comment]
It's much cleaner now! 

```
Clustered_DotPlot(
  seurat,
  features = pos_genes,
  colors_use_exp = viridis::inferno(20),
  colors_use_idents = cols_annotation,
  row_label_size = 6,
  column_label_size = 6,
  legend_label_size = 6,
  legend_title_size = 6,
  plot_km_elbow = FALSE,
  flip = TRUE
)
```

![image](https://user-images.githubusercontent.com/35916509/228482094-bb6cf770-58d0-45b7-8240-10a8b1ca3873.png)

The "Identity" title is mildly annoying but I can take it out with Inkscape for now.

Thanks so much for your efforts in this beautiful package!
