### ISSUE TITLE
Reorder clustered columns in Clustered_DotPlot()

### ISSUE THREAD

**Issue by ms-gx** [samuel-marsh/scCustomize#98]
Is there a way to reorder OR initially force the order of columns in `Clustered_DotPlot()` even when the columns are clustered?

Obviously, the order can not contradict with the dendrogram, which I will make sure.

I did this in `ComplexHeatmap` once, but was wondering if there is a relatively easy way to do this with your implementation?

**Comment by samuel-marsh** [comment]
Hi,

Sorry for delayed response.  Can you paste your previous complexheatmap code here?  I can see about adding parameter.

Thanks,
Sam

**Comment by samuel-marsh** [comment]
Hi @ms-gx,

Closing this for now as I haven't heard back.  But if you are still interested in this feature just post here and I'll reopen the issue and if could you please post your ComplexHeatmap code I will look into implementing the feature in scCustomize.

Thanks!
Sam
